/home/ben/B-CPP-500-PAR-5-2-rtype-axel.londas/src/server/src/ECS/src/System/ActualiseDrawable.cpp File Reference
#include "Registry.hpp"
#include "Position.hpp"
#include "Drawable.hpp"
#include "Controllable.hpp"
#include "Entity.hpp"
#include <SFML/Graphics.hpp>
Functions
void ActualiseDrawable (Registry &reg, Entity &e, sf::RenderWindow &window)
Function Documentation
ActualiseDrawable()
void ActualiseDrawable (Registry & reg, Entity & e, sf::RenderWindow & window)
Definition at line 15 of file ActualiseDrawable.cpp.
{
    Drawable &drawable = reg.get_component<Drawable>(e);
    Position &position = reg.get_component<Position>(e);
    // Velocity &velocity = reg.get_component<Velocity>(e);
    Controllable &controllable = reg.get_component<Controllable>(e);
    controllable.check_input();
    position.move(controllable);
    drawable.display(window, position);
}
References Controllable::check_input(), Drawable::display(), and Registry::get_component().