Drawable Class Reference
#include <Drawable.hpp>
Public Member Functions
Drawable ()=default
Drawable (const sf::Vector2f &scale)
void display (sf::RenderWindow &window, Position &_position)
void set_position (const Position &position)
void set_scale (const sf::Vector2f &scale)
void set_texture (sf::Texture &texture)
void draw (sf::RenderWindow &window, Position &pos)
Private Attributes
sf::Vector2f _scale = {1, 1}
sf::Sprite _sprite = sf::Sprite()
Detailed Description
Definition at line 16 of file Drawable.hpp.
Constructor & Destructor Documentation
Drawable() [1/2]
Drawable::Drawable () [default]
Drawable() [2/2]
Drawable::Drawable (const sf::Vector2f & scale)
Definition at line 10 of file Drawable.cpp.
{
    _scale = scale;
}
References _scale.
Member Function Documentation
display()
void Drawable::display (sf::RenderWindow & window, Position & _position)
Definition at line 31 of file Drawable.cpp.
{
    _sprite.setPosition(_position.x, _position.y);
    _sprite.setScale(_scale);
    window.draw(_sprite);
}
References _scale, _sprite, Position::x, and Position::y.
Referenced by ActualiseDrawable().
draw()
void Drawable::draw (sf::RenderWindow & window, Position & pos) [inline]
Definition at line 26 of file Drawable.hpp.
                                                         {
            _sprite.setPosition(pos.x, pos.y);
            window.draw(_sprite);
        }
References _sprite, Position::x, and Position::y.
Referenced by draw_system().
set_position()
void Drawable::set_position (const Position & position)
Definition at line 15 of file Drawable.cpp.
{
    _sprite.setPosition(position.x, position.y);
}
References _sprite, Position::x, and Position::y.
Referenced by draw_system(), and TestECSsfml().
set_scale()
void Drawable::set_scale (const sf::Vector2f & scale)
Definition at line 20 of file Drawable.cpp.
{
    _scale = scale;
    _sprite.setScale(_scale);
}
References _scale, and _sprite.
Referenced by MakeVinicius().
set_texture()
void Drawable::set_texture (sf::Texture & texture)
Definition at line 26 of file Drawable.cpp.
{
    _sprite.setTexture(texture);
}
References _sprite.
Referenced by MakeVinicius().
Member Data Documentation
_scale
sf::Vector2f Drawable::_scale = {1, 1} [private]
Definition at line 33 of file Drawable.hpp.
{1, 1};
Referenced by display(), Drawable(), and set_scale().
_sprite
sf::Sprite Drawable::_sprite = sf::Sprite() [private]
Definition at line 34 of file Drawable.hpp.
Referenced by display(), draw(), set_position(), set_scale(), and set_texture().
The documentation for this class was generated from the following files:
/home/ben/B-CPP-500-PAR-5-2-rtype-axel.londas/src/server/src/ECS/src/Data/Drawable.hpp
/home/ben/B-CPP-500-PAR-5-2-rtype-axel.londas/src/server/src/ECS/src/Data/Drawable.cpp