sparse_array< Component > Class Template Reference
#include <SparseArray.hpp>
Public Types
using value_type = Component
using reference_type = value_type &
using const_reference_type = value_type const &
using container_t = std::vector<value_type>
using size_type = typename container_t::size_type
using iterator = typename container_t::iterator
using const_iterator = typename container_t::const_iterator
using allocator_type = typename container_t::allocator_type
Public Member Functions
sparse_array ()
sparse_array (sparse_array const &)
sparse_array (sparse_array &&) noexcept
~sparse_array ()
sparse_array & operator= (sparse_array const &)
sparse_array & operator= (sparse_array &&) noexcept
reference_type operator[] (size_type idx)
const_reference_type operator[] (size_type idx) const
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end ()
const_iterator end () const
const_iterator cend () const
size_type size () const
reference_type insert_at (size_type idx, value_type const &value)
reference_type insert_at (size_type idx, value_type &&value)
template<class... Params>
reference_type emplace_at (size_type pos, Params &&...)
void erase (size_type pos)
size_type get_index (value_type const &) const
std::vector< value_type > const & get_storage () const
Private Attributes
container_t _data
Detailed Description
template<typename Component>
class sparse_array< Component >
Definition at line 20 of file SparseArray.hpp.
Member Typedef Documentation
allocator_type
template<typename Component >
using sparse_array< Component >::allocator_type = typename container_t::allocator_type
Definition at line 30 of file SparseArray.hpp.
const_iterator
template<typename Component >
using sparse_array< Component >::const_iterator = typename container_t::const_iterator
Definition at line 29 of file SparseArray.hpp.
const_reference_type
template<typename Component >
using sparse_array< Component >::const_reference_type = value_type const &
Definition at line 25 of file SparseArray.hpp.
container_t
template<typename Component >
using sparse_array< Component >::container_t = std::vector<value_type>
Definition at line 26 of file SparseArray.hpp.
iterator
template<typename Component >
using sparse_array< Component >::iterator = typename container_t::iterator
Definition at line 28 of file SparseArray.hpp.
reference_type
template<typename Component >
using sparse_array< Component >::reference_type = value_type &
Definition at line 24 of file SparseArray.hpp.
size_type
template<typename Component >
using sparse_array< Component >::size_type = typename container_t::size_type
Definition at line 27 of file SparseArray.hpp.
value_type
template<typename Component >
using sparse_array< Component >::value_type = Component
Definition at line 23 of file SparseArray.hpp.
Constructor & Destructor Documentation
sparse_array() [1/3]
template<typename Component >
sparse_array< Component >::sparse_array () [default]
sparse_array() [2/3]
template<typename Component >
sparse_array< Component >::sparse_array (sparse_array< Component > const &) [default]
sparse_array() [3/3]
template<typename Component >
sparse_array< Component >::sparse_array (sparse_array< Component > &&) [default], [noexcept]
~sparse_array()
template<typename Component >
sparse_array< Component >::~sparse_array () [default]
Member Function Documentation
begin() [1/2]
template<typename Component >
iterator sparse_array< Component >::begin ()
begin() [2/2]
template<typename Component >
const_iterator sparse_array< Component >::begin () const
cbegin()
template<typename Component >
const_iterator sparse_array< Component >::cbegin () const
cend()
template<typename Component >
const_iterator sparse_array< Component >::cend () const
emplace_at()
template<typename Component >
template<class... Params>
reference_type sparse_array< Component >::emplace_at (size_type pos, Params && ...)
end() [1/2]
template<typename Component >
iterator sparse_array< Component >::end ()
end() [2/2]
template<typename Component >
const_iterator sparse_array< Component >::end () const
erase()
template<typename Component >
void sparse_array< Component >::erase (size_type pos)
get_index()
template<typename Component >
size_type sparse_array< Component >::get_index (value_type const &) const
get_storage()
template<typename Component >
std::vector< value_type > const & sparse_array< Component >::get_storage () const
insert_at() [1/2]
template<typename Component >
reference_type sparse_array< Component >::insert_at (size_type idx, value_type && value)
insert_at() [2/2]
template<typename Component >
reference_type sparse_array< Component >::insert_at (size_type idx, value_type const & value)
Referenced by TestSparseArrayClass(), and TestSparseArrayInt().
operator=() [1/2]
template<typename Component >
sparse_array & sparse_array< Component >::operator= (sparse_array< Component > &&) [noexcept]
operator=() [2/2]
template<typename Component >
sparse_array & sparse_array< Component >::operator= (sparse_array< Component > const &)
operator[]() [1/2]
template<typename Component >
reference_type sparse_array< Component >::operator[] (size_type idx)
operator[]() [2/2]
template<typename Component >
const_reference_type sparse_array< Component >::operator[] (size_type idx) const
size()
template<typename Component >
size_type sparse_array< Component >::size () const
Referenced by TestSparseArrayInt().
Member Data Documentation
_data
template<typename Component >
container_t sparse_array< Component >::_data [private]
Definition at line 66 of file SparseArray.hpp.
The documentation for this class was generated from the following file:
/home/ben/B-CPP-500-PAR-5-2-rtype-axel.londas/src/server/src/ECS/src/SparseArray/SparseArray.hpp