Parsing Class Reference
A class to handle parsing of configuration files and command-line arguments.
#include <Parsing.hpp>
Public Member Functions
Parsing ()
Default constructor.
Parsing (int ac, char **av)
Constructor that initializes the Parsing class with command-line arguments.
~Parsing ()=default
Default destructor.
std::unordered_map< std::string, std::string > getServerSettings () const
Retrieves the server settings.
std::unordered_map< std::string, std::string > getClientSettings () const
Retrieves the client settings.
Private Member Functions
void getArgs (char **av)
Parses command-line arguments to extract server or client settings.
void getFileInfos (std::string &filename)
Parses a configuration file to extract settings.
Private Attributes
std::unordered_map< std::string, std::string > serverSettings
Stores server settings as key-value pairs.
std::unordered_map< std::string, std::string > clientSettings
Stores client settings as key-value pairs.
Detailed Description
A class to handle parsing of configuration files and command-line arguments.
This class parses and stores server and client settings from a configuration file or command-line arguments.
Definition at line 32 of file Parsing.hpp.
Constructor & Destructor Documentation
Parsing() [1/2]
Parsing::Parsing ()
Default constructor.
Default constructor implementation.
Definition at line 28 of file Parsing.cpp.
{}
Parsing() [2/2]
Parsing::Parsing (int ac, char ** av)
Constructor that initializes the Parsing class with command-line arguments.
Parameters
ac Argument count.
av Argument values.
Definition at line 35 of file Parsing.cpp.
{
    if (ac == 1) {
        std::string filename = "configuration_files/info.ini";
        getFileInfos(filename);
    } else if (ac == 2) {
        std::string filename = std::string(av[1]);
        getFileInfos(filename);
    } else {
        getArgs(av);
    }
}
References getArgs(), and getFileInfos().
~Parsing()
Parsing::~Parsing () [default]
Default destructor.
Member Function Documentation
getArgs()
void Parsing::getArgs (char ** av) [private]
Parses command-line arguments to extract server or client settings.
Parameters
av Command-line arguments.
Definition at line 52 of file Parsing.cpp.
{
    std::size_t cpt = 1;
    std::string current_argument = std::string(av[0]);
    std::string next_argument;
    if (current_argument == "r-type_server") {
        while (av[cpt]) {
            current_argument = std::string(av[cpt]);
            if (!av[cpt + 1]) {
                throw std::exception();
            }
            next_argument = std::string(av[cpt + 1]);
            serverSettings[current_argument.substr(2)] = next_argument;
            cpt += 2;
        }
    } else {
        while (av[cpt]) {
            current_argument = std::string(av[cpt]);
            if (!av[cpt + 1]) {
                throw std::exception();
            }
            next_argument = std::string(av[cpt + 1]);
            clientSettings[current_argument.substr(2)] = next_argument;
            cpt += 2;
        }
    }
}
References clientSettings, and serverSettings.
Referenced by Parsing().
getClientSettings()
std::unordered_map< std::string, std::string > Parsing::getClientSettings () const
Retrieves the client settings.
Returns
A map containing client settings as key-value pairs.
Definition at line 139 of file Parsing.cpp.
{
    return clientSettings;
}
References clientSettings.
Referenced by main().
getFileInfos()
void Parsing::getFileInfos (std::string & filename) [private]
Parses a configuration file to extract settings.
Parameters
filename The path to the configuration file.
Definition at line 85 of file Parsing.cpp.
{
    std::ifstream file(filename);
    if (!file.is_open()) {
        throw std::exception();
    }
    std::string line;
    std::string currentSection;
    while (std::getline(file, line)) {
        line.erase(0, line.find_first_not_of(" \t"));
        line.erase(line.find_last_not_of(" \t") + 1);
        if (line.empty() || line[0] == ';' || line[0] == '#') {
            continue;
        }
        if (line.front() == '[' && line.back() == ']') {
            currentSection = line.substr(1, line.size() - 2);
        } else {
            auto delimiterPos = line.find('=');
            if (delimiterPos != std::string::npos) {
                size_t commentPos = line.find_first_of(" \t\n;#");
                if (commentPos != std::string::npos) {
                    line = line.substr(0, commentPos);
                }
                std::string key = line.substr(0, delimiterPos);
                std::string value = line.substr(delimiterPos + 1);
                key.erase(0, key.find_first_not_of(" \t"));
                key.erase(key.find_last_not_of(" \t") + 1);
                value.erase(0, value.find_first_not_of(" \t"));
                value.erase(value.find_last_not_of(" \t") + 1);
                if (currentSection == "server") {
                    serverSettings[key] = value;
                } else if (currentSection == "Client") {
                    clientSettings[key] = value;
                }
            }
        }
    }
}
References clientSettings, and serverSettings.
Referenced by Parsing().
getServerSettings()
std::unordered_map< std::string, std::string > Parsing::getServerSettings () const
Retrieves the server settings.
Returns
A map containing server settings as key-value pairs.
Definition at line 130 of file Parsing.cpp.
{
    return serverSettings;
}
References serverSettings.
Referenced by main().
Member Data Documentation
clientSettings
std::unordered_map<std::string, std::string> Parsing::clientSettings [private]
Stores client settings as key-value pairs.
Definition at line 43 of file Parsing.hpp.
Referenced by getArgs(), getClientSettings(), and getFileInfos().
serverSettings
std::unordered_map<std::string, std::string> Parsing::serverSettings [private]
Stores server settings as key-value pairs.
Definition at line 38 of file Parsing.hpp.
Referenced by getArgs(), getFileInfos(), and getServerSettings().
The documentation for this class was generated from the following files:
/home/ben/B-CPP-500-PAR-5-2-rtype-axel.londas/src/Parsing/Parsing.hpp
/home/ben/B-CPP-500-PAR-5-2-rtype-axel.londas/src/Parsing/Parsing.cpp