Registry Class Reference
#include <Registry.hpp>
Public Member Functions
template<class Component >
sparse_array< Component > & register_component ()
template<class Component >
sparse_array< Component > & get_component ()
template<class Component >
sparse_array< Component > const & get_component () const
Entity spawn_entity ()
Entity entity_from_index (std::size_t index)
void kill_entity (Entity const &e)
template<typename Component >
void add_component (Entity const &to, Component &&c)
template<typename Component , typename... Params>
void emplace_component (Entity const &to, Params &&...p)
template<typename Component >
void remove_component (Entity const &from)
template<typename Component >
Component & get_component (Entity const &from)
template<typename Component >
Component const & get_component (Entity const &from) const
template<typename Component >
std::vector< Component > const & get_component_list () const
template<class... Components, typename Function >
void add_system (Function &&f)
template<class... Components, typename Function >
void add_system (Function const &f)
void run_systems ()
Private Member Functions
void erase_components (Entity const &e)
Private Attributes
std::unordered_map< std::type_index, std::any > _components_arrays
std::vector< std::function< void(Registry &, Entity const &)> > _erase_functions
std::vector< std::function< void(Registry &)> > _systems
std::queue< std::size_t > _free_ids
std::size_t _next_id = 0
Detailed Description
Definition at line 25 of file Registry.hpp.
Member Function Documentation
add_component()
template<typename Component >
void Registry::add_component (Entity const & to, Component && c)
Referenced by MakeVinicius(), and TestRegistry().
add_system() [1/2]
template<class... Components, typename Function >
void Registry::add_system (Function && f)
Referenced by TestECSsfml().
add_system() [2/2]
template<class... Components, typename Function >
void Registry::add_system (Function const & f)
emplace_component()
template<typename Component , typename... Params>
void Registry::emplace_component (Entity const & to, Params &&... p)
entity_from_index()
Entity Registry::entity_from_index (std::size_t index)
erase_components()
void Registry::erase_components (Entity const & e) [private]
Definition at line 28 of file Registry.cpp.
{
    for (auto &erase_function : _erase_functions) {
        erase_function(*this, e);
    }
}
References _erase_functions.
Referenced by kill_entity().
get_component() [1/4]
template<class Component >
sparse_array< Component > & Registry::get_component ()
Referenced by ActualiseDrawable(), control_system(), draw_system(), MakeVinicius(), and TestRegistry().
get_component() [2/4]
template<class Component >
sparse_array< Component > const & Registry::get_component () const
get_component() [3/4]
template<typename Component >
Component & Registry::get_component (Entity const & from)
get_component() [4/4]
template<typename Component >
Component const & Registry::get_component (Entity const & from) const
get_component_list()
template<typename Component >
std::vector< Component > const & Registry::get_component_list () const
Referenced by logging_system().
kill_entity()
void Registry::kill_entity (Entity const & e)
Definition at line 22 of file Registry.cpp.
{
    erase_components(e);
    _free_ids.push(e.get_id());
}
References _free_ids, erase_components(), and Entity::get_id().
register_component()
template<class Component >
sparse_array< Component > & Registry::register_component ()
Referenced by TestECSsfml(), and TestRegistry().
remove_component()
template<typename Component >
void Registry::remove_component (Entity const & from)
run_systems()
void Registry::run_systems ()
Definition at line 35 of file Registry.cpp.
{
    for (auto &system : _systems) {
        system(*this);
    }
}
References _systems.
Referenced by TestECSsfml().
spawn_entity()
Entity Registry::spawn_entity ()
Definition at line 10 of file Registry.cpp.
{
    std::size_t id;
    if (!_free_ids.empty()) {
        id = _free_ids.front();
        _free_ids.pop();
    } else {
        id = _next_id++;
    }
    return Entity(id);
}
References _free_ids, and _next_id.
Referenced by MakeVinicius(), and TestRegistry().
Member Data Documentation
_components_arrays
std::unordered_map<std::type_index, std::any> Registry::_components_arrays [private]
Definition at line 67 of file Registry.hpp.
_erase_functions
std::vector<std::function<void(Registry &, Entity const &)> > Registry::_erase_functions [private]
Definition at line 68 of file Registry.hpp.
Referenced by erase_components().
_free_ids
std::queue<std::size_t> Registry::_free_ids [private]
Definition at line 70 of file Registry.hpp.
Referenced by kill_entity(), and spawn_entity().
_next_id
std::size_t Registry::_next_id = 0 [private]
Definition at line 71 of file Registry.hpp.
Referenced by spawn_entity().
_systems
std::vector<std::function<void(Registry &)> > Registry::_systems [private]
Definition at line 69 of file Registry.hpp.
Referenced by run_systems().
The documentation for this class was generated from the following files:
/home/ben/B-CPP-500-PAR-5-2-rtype-axel.londas/src/server/src/ECS/src/Registry/Registry.hpp
/home/ben/B-CPP-500-PAR-5-2-rtype-axel.londas/src/server/src/ECS/src/Registry/Registry.cpp