NetworkServer Class Reference
A class to handle UDP networking functionalities.
#include <NetworkServer.hpp>
Public Member Functions
NetworkServer (unsigned short port_)
Constructor that initializes the server with a specified port.
~NetworkServer ()
Destructor for cleaning up resources.
void sendMessage (std::string &message)
Sends a message to the destination endpoint.
void startAsyncReceive (std::function< void(const std::string &)> callback)
Starts an asynchronous receive operation.
asio::io_context & getIoContext ()
Retrieves the ASIO I/O context.
Private Attributes
asio::io_context io_context
ASIO I/O context for managing asynchronous operations.
asio::ip::udp::socket socket
UDP socket used for communication.
asio::ip::udp::endpoint destination
Destination endpoint for sending messages.
unsigned short port
Port number on which the server listens.
Detailed Description
A class to handle UDP networking functionalities.
This class manages sending and receiving messages over a UDP socket using ASIO.
Definition at line 34 of file NetworkServer.hpp.
Constructor & Destructor Documentation
NetworkServer()
NetworkServer::NetworkServer (unsigned short port_)
Constructor that initializes the server with a specified port.
Construct a new NetworkServer object.
Parameters
port_ The port number to bind the server.
Opens and binds a UDP socket to the specified port.
Parameters
port_ The port to bind the server to.
Exceptions
ServerWrongSocket Thrown if the socket cannot be opened or bound.
Definition at line 34 of file NetworkServer.cpp.
                                                 : io_context(), socket(io_context), port(port_)
{
    try
    {
        socket.open(asio::ip::udp::v4());
        socket.bind(asio::ip::udp::endpoint(asio::ip::udp::v4(), port));
    }
    catch(const std::exception& e)
    {
        throw ServerWrongSocket();
    }
}
References port, and socket.
~NetworkServer()
NetworkServer::~NetworkServer ()
Destructor for cleaning up resources.
Destroy the NetworkServer object.
Closes the socket if it is open and outputs a shutdown message.
Definition at line 52 of file NetworkServer.cpp.
{
    try
    {
        if (socket.is_open()) {
            socket.close();
        }
        std::cout << "Fermeture du serveur." << std::endl;
    }
    catch(const std::exception& e)
    {
        std::cerr << ServerWrongSocket() << std::endl;
        std::cerr << "Fermeture du serveur" << std::endl;
    }
}
References socket.
Member Function Documentation
getIoContext()
asio::io_context & NetworkServer::getIoContext ()
Retrieves the ASIO I/O context.
Get the io_context associated with the server.
Returns
Reference to the ASIO I/O context.
A reference to the server's asio::io_context.
Definition at line 110 of file NetworkServer.cpp.
                                            {
    return io_context;
}
References io_context.
Referenced by main().
sendMessage()
void NetworkServer::sendMessage (std::string & message)
Sends a message to the destination endpoint.
Sends a message to the configured destination.
Parameters
message The message to be sent.
message The message to send as a string.
Exceptions
ServerWrongSend Thrown if the message cannot be sent.
Definition at line 74 of file NetworkServer.cpp.
{
    try
    {
        socket.send_to(asio::buffer(message), destination);
    }
    catch(const std::exception& e)
    {
        std::cerr << ServerWrongSend() << std::endl;
    }
}
References destination, and socket.
Referenced by handleReceivedMessage().
startAsyncReceive()
void NetworkServer::startAsyncReceive (std::function< void(const std::string &)> callback)
Starts an asynchronous receive operation.
Parameters
callback Function to handle the received message.
This function sets up a callback to handle incoming messages asynchronously.
Parameters
callback A function to call when a message is received. The function takes a string containing the received message.
Definition at line 93 of file NetworkServer.cpp.
                                                                                  {
    auto buffer = std::make_shared<std::vector<char>>(BUFFER_SIZE);
    socket.async_receive_from(asio::buffer(*buffer), destination, [this, buffer, callback](std::error_code ec, std::size_t bytes_received) {
            if (!ec && bytes_received > 0) {
                callback(std::string(buffer->data(), bytes_received));
            } else {
                std::cerr << "Erreur lors de la réception : " << ec.message() << std::endl;
            }
            startAsyncReceive(callback);
        });
}
References BUFFER_SIZE, destination, socket, and startAsyncReceive().
Referenced by main(), and startAsyncReceive().
Member Data Documentation
destination
asio::ip::udp::endpoint NetworkServer::destination [private]
Destination endpoint for sending messages.
Definition at line 50 of file NetworkServer.hpp.
Referenced by sendMessage(), and startAsyncReceive().
io_context
asio::io_context NetworkServer::io_context [private]
ASIO I/O context for managing asynchronous operations.
Definition at line 40 of file NetworkServer.hpp.
Referenced by getIoContext().
port
unsigned short NetworkServer::port [private]
Port number on which the server listens.
Definition at line 55 of file NetworkServer.hpp.
Referenced by NetworkServer().
socket
asio::ip::udp::socket NetworkServer::socket [private]
UDP socket used for communication.
Definition at line 45 of file NetworkServer.hpp.
Referenced by NetworkServer(), sendMessage(), startAsyncReceive(), and ~NetworkServer().
The documentation for this class was generated from the following files:
/home/ben/B-CPP-500-PAR-5-2-rtype-axel.londas/src/server/src/network/NetworkServer.hpp
/home/ben/B-CPP-500-PAR-5-2-rtype-axel.londas/src/server/src/network/NetworkServer.cpp