/home/ben/B-CPP-500-PAR-5-2-rtype-axel.londas/src/client/main.cpp File Reference
#include <iostream>
#include "src/network/NetworkClient.hpp"
#include "../Parsing/Parsing.hpp"
Functions
int main (int ac, char **av)
Function Documentation
main()
int main (int ac, char ** av)
Definition at line 22 of file main.cpp.
                            {
    Parsing parser(ac, av);
    auto clientSettings = parser.getClientSettings();
    unsigned short port = std::stoi(clientSettings["port"]);
    std::string host = clientSettings["host"];
    NetworkClient client(port, host);
    std::cout << "Client connecté à " << host << ":" << port << std::endl;
    while (true) {
        std::string message;
        std::cout << "Entrez un message à envoyer au serveur : ";
        std::getline(std::cin, message);
        while (message.empty()) {
            std::cerr << ClientWrongSend() << std::endl;
            std::cout << "Entrez un message à envoyer au serveur : ";
            std::getline(std::cin, message);
        }
        if (message == "exit") {
            break;
        }
        client.sendMessage(message);
        std::string response = client.receiveMessage();
        if (!response.empty()) {
            std::cout << "Réponse du serveur : " << response << std::endl;
        }
    }
    return 0;
}
References Parsing::getClientSettings(), NetworkClient::receiveMessage(), and NetworkClient::sendMessage().