/home/ben/B-CPP-500-PAR-5-2-rtype-axel.londas/src/server/src/ECS/src/System/control_system.cpp File Reference
#include "Registry.hpp"
#include "Drawable.hpp"
Functions
void control_system (Registry &r)
Function Documentation
control_system()
void control_system (Registry & r)
Definition at line 11 of file control_system.cpp.
{
    auto &controllables = r.get_component<Controllable>();
    for (std::size_t i = 0; i < controllables.size(); ++i) {
            Controllable &controllable = controllables[i];
            controllable.check_input();
    }
}
References Controllable::check_input(), and Registry::get_component().
Referenced by TestECSsfml().