/home/ben/B-CPP-500-PAR-5-2-rtype-axel.londas/src/server/src/ECS/src/System/draw_system.cpp File Reference
#include "Registry.hpp"
#include "Position.hpp"
#include "Drawable.hpp"
#include "Controllable.hpp"
#include <SFML/Graphics.hpp>
Functions
void draw_system (Registry &r, sf::RenderWindow &window)
Function Documentation
draw_system()
void draw_system (Registry & r, sf::RenderWindow & window)
Definition at line 14 of file draw_system.cpp.
{
    auto &positions = r.get_component<Position>();
    auto &drawables = r.get_component<Drawable>();
    auto &controllables = r.get_component<Controllable>();
    for (size_t i = 0; i < positions.size() && i < drawables.size() && i < drawables.size(); ++i) {
        Position &pos = positions[i];
        Drawable &drawable = drawables[i];
        Controllable &controllable = controllables[i];
        
        pos.move(controllable);
        drawable.set_position(pos);
        drawable.draw(window, pos);
    }
}
References Drawable::draw(), Registry::get_component(), Position::move(), and Drawable::set_position().
Referenced by TestECSsfml().