/home/ben/B-CPP-500-PAR-5-2-rtype-axel.londas/src/server/src/ECS/src/System/MakeVinicius.cpp File Reference
#include "Registry.hpp"
#include "Position.hpp"
#include "Velocity.hpp"
#include "Drawable.hpp"
#include "Controllable.hpp"
#include "Entity.hpp"
#include <SFML/Graphics.hpp>
Functions
Entity MakeVinicius (Registry &r, sf::Vector2f &position, sf::Vector2f &size, sf::Vector2f &velocity, sf::Texture &texture)
Function Documentation
MakeVinicius()
Entity MakeVinicius (Registry & r, sf::Vector2f & position, sf::Vector2f & size, sf::Vector2f & velocity, sf::Texture & texture)
Definition at line 16 of file MakeVinicius.cpp.
{
    Entity Vinicius = r.spawn_entity();
    r.add_component(Vinicius, Drawable({size.x, size.y}));
    r.add_component(Vinicius, Controllable());
    r.add_component(Vinicius, Position(position.x, position.y));
    r.add_component(Vinicius, Velocity(velocity.x, velocity.y));
    Drawable &drawable = r.get_component<Drawable>(Vinicius);
    drawable.set_texture(texture);
    drawable.set_scale({size.x, size.y});
    return Vinicius;
}
References Registry::add_component(), Registry::get_component(), Drawable::set_scale(), Drawable::set_texture(), and Registry::spawn_entity().
Referenced by TestECSsfml().