/home/ben/B-CPP-500-PAR-5-2-rtype-axel.londas/src/server/main.cpp File Reference
#include <iostream>
#include "src/network/NetworkServer.hpp"
#include "src/thread/ThreadPool.hpp"
#include "../Parsing/Parsing.hpp"
#include <thread>
#include <vector>
Functions
void handleReceivedMessage (NetworkServer &server, ThreadPool &threadPool, const std::string &message)
int main (int ac, char **av)
Function Documentation
handleReceivedMessage()
void handleReceivedMessage (NetworkServer & server, ThreadPool & threadPool, const std::string & message)
Definition at line 25 of file main.cpp.
                                                                                                    {
    threadPool.enqueue([&server, message]() {
        std::cout << "Message reçu : " << message << std::endl;
        std::string response = "Confirmation : Message reçu !";
        server.sendMessage(response);
    });
}
References ThreadPool::enqueue(), and NetworkServer::sendMessage().
Referenced by main().
main()
int main (int ac, char ** av)
Definition at line 33 of file main.cpp.
                            {
    try {
        Parsing parser(ac, av);
        auto serverSettings = parser.getServerSettings();
        unsigned short port = std::stoi(serverSettings["port"]);
        NetworkServer server(port);
        std::cout << "Serveur démarré sur le port " << port << std::endl;
        unsigned int num_threads = std::thread::hardware_concurrency();
        ThreadPool threadPool(num_threads);
        server.startAsyncReceive([&server, &threadPool](const std::string& message) {
            handleReceivedMessage(server, threadPool, message);
        });
        server.getIoContext().run();
    } catch (const std::exception& e) {
        std::cerr << "Erreur : " << e.what() << '\n';
    }
    return 0;
}
References NetworkServer::getIoContext(), Parsing::getServerSettings(), handleReceivedMessage(), and NetworkServer::startAsyncReceive().