/home/ben/B-CPP-500-PAR-5-2-rtype-axel.londas/src/server/src/ECS/src/TestCode/TestECSsfml.cpp File Reference
#include <iostream>
#include "Registry.hpp"
#include "Position.hpp"
#include "Velocity.hpp"
#include "Drawable.hpp"
#include "Controllable.hpp"
#include <unistd.h>
#include <limits.h>
#include <SFML/Graphics.hpp>
Functions
void logging_system (Registry &r)
void ActualiseDrawable (Registry &reg, Entity &e, sf::RenderWindow &window)
Entity MakeVinicius (Registry &r, sf::Vector2f &position, sf::Vector2f &size, sf::Vector2f &velocity, sf::Texture &texture)
void draw_system (Registry &r, sf::RenderWindow &window)
void control_system (Registry &r)
std::string get_current_working_dir ()
void TestECSsfml ()
Function Documentation
ActualiseDrawable()
void ActualiseDrawable (Registry & reg, Entity & e, sf::RenderWindow & window)
Definition at line 15 of file ActualiseDrawable.cpp.
{
    Drawable &drawable = reg.get_component<Drawable>(e);
    Position &position = reg.get_component<Position>(e);
    // Velocity &velocity = reg.get_component<Velocity>(e);
    Controllable &controllable = reg.get_component<Controllable>(e);
    controllable.check_input();
    position.move(controllable);
    drawable.display(window, position);
}
References Controllable::check_input(), Drawable::display(), and Registry::get_component().
control_system()
void control_system (Registry & r)
Definition at line 11 of file control_system.cpp.
{
    auto &controllables = r.get_component<Controllable>();
    for (std::size_t i = 0; i < controllables.size(); ++i) {
            Controllable &controllable = controllables[i];
            controllable.check_input();
    }
}
References Controllable::check_input(), and Registry::get_component().
Referenced by TestECSsfml().
draw_system()
void draw_system (Registry & r, sf::RenderWindow & window)
Definition at line 14 of file draw_system.cpp.
{
    auto &positions = r.get_component<Position>();
    auto &drawables = r.get_component<Drawable>();
    auto &controllables = r.get_component<Controllable>();
    for (size_t i = 0; i < positions.size() && i < drawables.size() && i < drawables.size(); ++i) {
        Position &pos = positions[i];
        Drawable &drawable = drawables[i];
        Controllable &controllable = controllables[i];
        
        pos.move(controllable);
        drawable.set_position(pos);
        drawable.draw(window, pos);
    }
}
References Drawable::draw(), Registry::get_component(), Position::move(), and Drawable::set_position().
Referenced by TestECSsfml().
get_current_working_dir()
std::string get_current_working_dir ()
Definition at line 18 of file TestECSsfml.cpp.
{
    char cwd[PATH_MAX];
    if (getcwd(cwd, sizeof(cwd)) != NULL) {
        return std::string(cwd);
    } else {
        perror("getcwd() error");
        return "";
    }
}
Referenced by TestECSsfml().
logging_system()
void logging_system (Registry & r)
Definition at line 14 of file logging_system.cpp.
{
    std::vector<Position> positions = r.get_component_list<Position>();
    std::vector<Velocity> velocities = r.get_component_list<Velocity>();
    std::cout << positions.size() << " positions and " << velocities.size() << " velocities." << std::endl;
    for (size_t i = 0; i < positions.size() && i < velocities.size(); ++i) {
        Position pos = positions[i];
        Velocity vel = velocities[i];
        std::cerr << i << ": " << pos << " | " << vel << std::endl;
    }
}
References Registry::get_component_list().
Referenced by TestECSsfml().
MakeVinicius()
Entity MakeVinicius (Registry & r, sf::Vector2f & position, sf::Vector2f & size, sf::Vector2f & velocity, sf::Texture & texture)
Definition at line 16 of file MakeVinicius.cpp.
{
    Entity Vinicius = r.spawn_entity();
    r.add_component(Vinicius, Drawable({size.x, size.y}));
    r.add_component(Vinicius, Controllable());
    r.add_component(Vinicius, Position(position.x, position.y));
    r.add_component(Vinicius, Velocity(velocity.x, velocity.y));
    Drawable &drawable = r.get_component<Drawable>(Vinicius);
    drawable.set_texture(texture);
    drawable.set_scale({size.x, size.y});
    return Vinicius;
}
References Registry::add_component(), Registry::get_component(), Drawable::set_scale(), Drawable::set_texture(), and Registry::spawn_entity().
Referenced by TestECSsfml().
TestECSsfml()
void TestECSsfml ()
Definition at line 29 of file TestECSsfml.cpp.
{
    sf::RenderWindow window(sf::VideoMode(800, 600), "SFML Window");
    window.setFramerateLimit(60);
    std::string cwd = get_current_working_dir();
    Registry reg;
    reg.register_component<Drawable>();
    reg.register_component<Position>();
    reg.register_component<Velocity>();
    reg.register_component<Controllable>();
    sf::Texture texture;
    if (!texture.loadFromFile(cwd + "/asset/Costume_Rouge_Vinicius.png")) {
        std::cerr << "Error: Could not load texture from file " << cwd + "/asset/Costume_Rouge_Vinicius.png" << std::endl;
    }
    sf::Vector2f position(150, 100);
    sf::Vector2f position2(300, 300);
    sf::Vector2f velocity(1, 1);
    sf::Vector2f size(1, 1);
    sf::Vector2f size2(0.5, 0.5);
    Entity Vinicius = MakeVinicius(reg, position, size, velocity, texture);
    Entity ViniciusJr = MakeVinicius(reg, position2, size2, velocity, texture);
    logging_system(reg);
    reg.add_system<Position, Velocity>([](auto &positions, auto &velocities) {
        for (std::size_t i = 0; i < positions.size(); ++i) {
                Position &pos = positions[i];
                Velocity &vel = velocities[i];
                pos.x += vel.x;
                pos.y += vel.y;
        }
    });
    reg.add_system<Drawable, Position>([](auto &drawables, auto &positions) {
        for (std::size_t i = 0; i < drawables.size(); ++i) {
            Drawable &drawable = drawables[i];
            Position &position = positions[i];
            drawable.set_position(position);
        }
    });
    while (window.isOpen()) {
        sf::Event event;
        while (window.pollEvent(event)) {
            if (event.type == sf::Event::Closed)
                window.close();
        }
        reg.run_systems();
        window.clear(sf::Color::Black);
        control_system(reg);
        draw_system(reg, window);
        window.display();
    }
}
References Registry::add_system(), control_system(), draw_system(), get_current_working_dir(), logging_system(), MakeVinicius(), Registry::register_component(), Registry::run_systems(), Drawable::set_position(), Position::x, Velocity::x, Position::y, and Velocity::y.