/home/ben/B-CPP-500-PAR-5-2-rtype-axel.londas/src/server/src/ECS/src/TestCode/TestRegistry.cpp File Reference
#include <iostream>
#include "Registry.hpp"
#include "Position.hpp"
#include "Velocity.hpp"
Functions
void TestRegistry ()
Function Documentation
TestRegistry()
void TestRegistry ()
Definition at line 13 of file TestRegistry.cpp.
{
    Registry reg;
    reg.register_component<Position>();
    reg.register_component<Velocity>();
    Entity e = reg.spawn_entity();
    reg.add_component(e, Position(40, 40));
    reg.add_component(e, Velocity(42, 42));
    // to understand kill_entity uncomment the following line same for remove_component
    // reg.kill_entity(e);
    //reg.remove_component<Position>(e);
    // reg.remove_component<Velocity>(e);
    Position &pos = reg.get_component<Position>(e);
    Velocity &vel = reg.get_component<Velocity>(e);
    std::cout << pos.x << std::endl;
    std::cout << pos.y << std::endl;
    std::cout << vel.x << std::endl;
    std::cout << vel.y << std::endl;
}
References Registry::add_component(), Registry::get_component(), Registry::register_component(), Registry::spawn_entity(), Position::x, and Position::y.