FROM alpine:latest

RUN apk add --no-cache cmake build-base asio-dev git libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libogg-dev mesa-dev eudev-dev openal-soft-dev freetype-dev

WORKDIR /app

RUN mkdir -p build

COPY . /app

WORKDIR /app/build

CMD sh -c "cmake .. && cd .. && cmake --build build"
